### ISSUE TITLE
Cloudpebble : Cannot find module 'message_keys'

### ISSUE THREAD

**Issue by zszen** [pebble/clay#118]
[PHONE] pebble-app.js:?: JavaScript Error:
Error: Cannot find module 'message_keys'
    at Object.loader.require (loader.js:66:11)
    at _require.require (loader.js:54:48)
    at o (node_modules/pebble-clay/index.js:2:419)
    at node_modules/pebble-clay/index.js:2:610
    at Object.pebble-clay../package.json (node_modules/pebble-clay/index.js:15:1563)
    at o (node_modules/pebble-clay/index.js:2:559)
    at e (node_modules/pebble-clay/index.js:2:726)
    at node_modules/pebble-clay/index.js:2:743
    at c (node_modules/pebble-clay/index.js:2:85)
    at Object.loader (node_modules/pebble-clay/index.js:2:282)

**Comment by keegan-lillo** [comment]
Can you please provide more context? That error is not a Clay error. the `message_keys` module is provided at run time to the `app.js`by cloudpebble

**Comment by zszen** [comment]
a empty project
app.js:

> var Clay = require('pebble-clay');
> var clayConfig = require('./config');
> var clay = new Clay(clayConfig);

config.js:

> //config page
> module.exports = [];

**Comment by zszen** [comment]
fix it : CONFIGURABLE need checked

**Comment by sirlantis** [comment]
@keegan-lillo Ran into a similar issue, even though I had Configurable enabled and was using automatic assignment. The workaround was to create `dummy` key entry.

**Comment by keegan-lillo** [comment]
Clay now sets configurable itself so this shouldn't be an issue at all anymore. Maybe this is a cloudpebble bug?
